version: 2
jobs:
   build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
         name: build
         command: chmod +x ./scripts/build.sh
     
      - run:
          name: build the maven project
          command: ./scripts/build.sh

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
         name: deploy
         command: chmod +x ./scripts/deploy.sh
      
      - run:
          name: deploy the maven project
          command: ./scripts/deploy.sh
          
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
         name: test
         command: chmod +x ./scripts/test.sh
      
      - run:
         name: test the maven project
         command: ./scripts/test.sh
         
          
          

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - deploy
