version: 2

dependencies:
override:
- mvn --fail-never dependency:go-offline || true

jobs:

  cache:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: c-{{ checksum "pom.xml" }}
     
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: c -{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
          
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
         name: build chmod permission
         command: chmod +x ./scripts/build.sh
     
      - run:
          name: build the maven project
          command: ./scripts/build.sh

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
         name: deploy chmod permission
         command: chmod +x ./scripts/deploy.sh
      
      - run:
          name: deploy the maven project
          command: ./scripts/deploy.sh
          
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
         name: test chmod permission
         command: chmod +x ./scripts/test.sh
      
      - run:
         name: test the maven project
         command: ./scripts/test.sh
         
         


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - cache:
          requires:
            - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
           - cache
           - test
      
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
       
