version: 2
jobs:
  build:
    
    working_directory: ~/ci

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout
      
      - run:
          name: build the maven project
          command: ./scripts/build.sh
